Paths:
  spline:
    win:
      cpu:
        ast: /source/mleFit_LM_DLL/CPUmleFit_LM.dll
      cuda:
        ast: /source/mleFit_LM_DLL/GPUmleFit_LM.dll
    mac:
      cpu:
        ast: /source/mleFit_LM_dylib/libCPUmleFit_LM.dylib
    linux:
      cpu:
        ast: /source/mleFit_LM_so/libCPUmleFit_LM.so
      cuda:
        ast: /source/mleFit_LM_so/libGPUmleFit_LM.so

main_data_dir:
  E:/EMBL files/data for PSF learning/ # main folder to your data, it is only useful if all your data are saved in one location, see example file
