Params:
  model:
    psf_type: zernike_vector
    loss_weight:
      smooth: 0
      lateral_drift_weight: 0.1
    rej_threshold:
      bias_z: 3
      mse: 3
      photon: 1.5
    psf:
      estimate_photon_variation: true
