Params:
  io:
    data_path: ""
    keyword: "Default."
    output_path: ""
    subfolder: ""
    format: .tif
    variable_name: ""
    filelist: []

  data:
    camera_gain: 0.2
    camera_offset: 398.6
    stage_movement_direction: normal
    swap_xy_dimensions: false
    emission_wavelength: 0.68
    numerical_aperture: 1.43
    refractive_indices:
      immersion: 1.516
      medium: 1.335
      coverslip: 1.516
    pixel_size:
      x: 0.127
      y: 0.116
      z: 0.05
    lattice_light_sheet:
      skew_translation_per_slice: [0,0]

  selection:
    roi:
      roi_size: [21,21]
      gauss_sigma: [2,2]
      max_kernel: [3,3]
      peak_height: 0.2
      max_bead_number: 40
      bead_radius: 0.0
    FOV:
      y_center: 0
      x_center: 0
      radius: 0
      z_start: 0
      z_end: -0
      z_step: 1

  model:
    psf_type: zernike
    psf:
      pupil_size: 64
      max_zernike_order: 8
      # zernike_polynomials: [[1,1],[0,2],[2,2]]
      extra_blur_sigma: 0.5
      include_apodization: true
      constant_pupil_magnitude: false
      radially_symmetric_magnitude: false
      include_index_mismatch: false
      initial_pupil_file_path: ""
      estimate_drift: false
      estimate_photon_variation: false
      pixel_upsampling_factor: 2
    loss_weight:
      mse_weight: 1
      modified_mse_weight: 1
      smooth: 0
      edge: 0.01
      psf_positivity_weight: 1
      background_positivity_weight: 1
      photon_positivity_weight: 1
      intensity_normalization_weight: 0
      lateral_drift_weight: 10
    rej_threshold:
      bias_z: 0.99
      mse: 0.8
      photon: 1.5

  runtime:
    use_cuda: true
    batch_size: 1600
    max_iterations: 200
    enable_relearning: true
    enable_localization: false
    plot_all_steps: false
