Params:
  io:
    datapath: ""
    keyword: "Default."
    savename: ""
    subfolder: ""
    format: .tif
    varname: ""
    filelist: []

  data:
    gain: 0.2
    ccd_offset: 398.6
    stage_mov_dir: normal
    swapxy: false
    emission_wavelength: 0.68
    NA: 1.43
    RI:
      imm: 1.516
      med: 1.335
      cov: 1.516
    pixel_size:
      x: 0.127
      y: 0.116
      z: 0.05
    LLS:
      skew_const: [0,0]

  selection:
    roi:
      roi_size: [21,21]
      gauss_sigma: [2,2]
      max_kernel: [3,3]
      peak_height: 0.2
      max_bead_number: 40
      bead_radius: 0.0
    FOV:
      y_center: 0
      x_center: 0
      radius: 0
      z_start: 0
      z_end: -0
      z_step: 1

  model:
    PSFtype: zernike
    psf:
      pupilsize: 64
      n_max: 8
      blur_sigma: 0.5
      with_apoid: true
      const_pupilmag: false
      symmetric_mag: false
      with_IMM: false
      init_pupil_file: ""
      estimate_drift: false
      var_photon: false
      bin: 2
    loss_weight:
      mse1: 1
      mse2: 1
      smooth: 0
      edge: 0.01
      psf_min: 1
      bg_min: 1
      photon_min: 1
      Inorm: 0
      gxy_min: 10
    rej_threshold:
      bias_z: 0.99
      mse: 0.8
      photon: 1.5

  runtime:
    usecuda: true
    batch_size: 1600
    iteration: 200
    relearn: true
    plotall: false
