Params:
  io:
    format: .mat
  data:
    stage_movement_direction: reverse
    pixel_size:
      x: 0.129
      y: 0.129
    emission_wavelength: 0.6
    numerical_aperture: 1.35
    refractive_indices:
      immersion: 1.406
      medium: 1.406
      coverslip: 1.516
  selection:
    roi:
      roi_size: [21,21]
      gauss_sigma: [2,2]
      max_kernel: [3,3]
