Params:
  io:
    format: .mat
  data:
    stage_mov_dir: reverse
    pixel_size:
      x: 0.129
      y: 0.129
    emission_wavelength: 0.6
    NA: 1.35
    RI:
      imm: 1.406
      med: 1.406
      cov: 1.516
  selection:
    roi:
      roi_size: [21,21]
      gauss_sigma: [2,2]
      max_kernel: [3,3]
