Params:
  io:
    format: .tif
  data:
    pixel_size:
      x: 0.11
      y: 0.11
    swap_xy_dimensions: true
    emission_wavelength: 0.68
    numerical_aperture: 1.5
    refractive_indices:
      immersion: 1.515
      medium: 1.406
      coverslip: 1.525
  selection:
    roi:
      roi_size: [31,31]
      gauss_sigma: [2,2]
      max_kernel: [3,3]
  model:
    psf:
      max_zernike_order: 6
