Params:
  io:
    format: .tif
  data:
    pixel_size:
      x: 0.108
      y: 0.108
    swapxy: false
    emission_wavelength: 0.67
    NA: 1.35
    RI:
      imm: 1.406
      med: 1.406
      cov: 1.524
  selection:
    roi:
      roi_size: [23,23]
      gauss_sigma: [2,2]
      max_kernel: [3,3]
  model:
    psf:
      n_max: 8
