Params:
  io:
    format: .tif
  data:
    pixel_size:
      x: 0.108
      y: 0.108
    swap_xy_dimensions: false
    emission_wavelength: 0.67
    numerical_aperture: 1.35
    refractive_indices:
      immersion: 1.406
      medium: 1.406
      coverslip: 1.524
  selection:
    roi:
      roi_size: [23,23]
      gauss_sigma: [2,2]
      max_kernel: [3,3]
  model:
    psf:
      max_zernike_order: 8
