Params:
  io:
    format: .tiff
  data:
    pixel_size:
      x: 0.104
      y: 0.104
    LLS:
      skew_const: [0,-0.7845]
    emission_wavelength: 0.6
    NA: 1.1
    RI:
      imm: 1.334
      med: 1.334
      cov: 1.334
  selection:
    roi:
      roi_size: [37,27,27]
      gauss_sigma: [6,2,2]
      max_kernel: [9,3,3]
  model:
    psf:
      estimate_drift: true
