Params:
  io:
    format: .tiff
  data:
    pixel_size:
      x: 0.104
      y: 0.104
    lattice_light_sheet:
      skew_translation_per_slice: [0,-0.7845]
    emission_wavelength: 0.6
    numerical_aperture: 1.1
    refractive_indices:
      immersion: 1.334
      medium: 1.334
      coverslip: 1.334
  selection:
    roi:
      roi_size: [37,27,27]
      gauss_sigma: [6,2,2]
      max_kernel: [9,3,3]
  model:
    psf:
      estimate_drift: true
