Params:
  io:
    format: .tif
  data:
    pixel_size:
      x: 0.127
      y: 0.116
    swapxy: true
    emission_wavelength: 0.6
    NA: 1.43
    RI:
      imm: 1.516
      med: 1.335
      cov: 1.516
  selection:
    roi:
      roi_size: [25,25]
      gauss_sigma: [2,2]
      max_kernel: [3,3]
    FOV:
      z_start: 1
      z_end: -1
