Params:
  io:
    format: .tif
  data:
    pixel_size:
      x: 0.127
      y: 0.116
    swap_xy_dimensions: true
    emission_wavelength: 0.6
    numerical_aperture: 1.43
    refractive_indices:
      immersion: 1.516
      medium: 1.335
      coverslip: 1.516
  selection:
    roi:
      roi_size: [25,25]
      gauss_sigma: [2,2]
      max_kernel: [3,3]
    FOV:
      z_start: 1
      z_end: -1
