Params:
  io:
    format: .tif
  data:
    pixel_size:
      x: 0.123
      y: 0.123
    swap_xy_dimensions: false
    emission_wavelength: 0.6
    numerical_aperture: 1.35
    refractive_indices:
      immersion: 1.406
      medium: 1.35
      coverslip: 1.516
  selection:
    roi:
      roi_size: [31,31]
      gauss_sigma: [2,2]
      max_kernel: [3,3]
