Params:
  io:
    format: .tif
  data:
    pixel_size:
      x: 0.123
      y: 0.123
    swapxy: false
    emission_wavelength: 0.6
    NA: 1.35
    RI:
      imm: 1.406
      med: 1.35
      cov: 1.516
  selection:
    roi:
      roi_size: [31,31]
      gauss_sigma: [2,2]
      max_kernel: [3,3]
