Params:
  io:
    format: .tif
  data:
    pixel_size:
      x: 0.12
      y: 0.12
    emission_wavelength: 0.607
    numerical_aperture: 1.4
    refractive_indices:
      immersion: 1.515
      medium: 1.56
      coverslip: 1.515
  selection:
    roi:
      roi_size: [21,21]
      gauss_sigma: [2,2]
      max_kernel: [3,3]
    FOV:
      z_start: 10
      z_end: -3
  model:
    psf:
      max_zernike_order: 6
